name: Windows CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Set Chrome Binary Path
        run: |
          mkdir "C:\Program Files (x86)\Google\Chrome"
          cmd /c mklink /D "C:\Program Files (x86)\Google\Chrome\Application" "C:\Program Files\Google\Chrome\Application"
      - name: Percy Test
        uses: percy/exec-action@master
        with:
           command: "wdio wdio.conf.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
